site_name: KubeSail Docs
theme: readthedocs
repo_url: https://github.com/kubesail/docs
nav:
      - Home: README.md
      - Repos: repo_builder.md
      - Clusters: "byoc.md"
      - Domains: domains.md
      - Templates: templates.md
      - Platform: platform.md
      - Troubleshooting: troubleshooting.md
      - PiBox: pibox.md
      - Advanced Topics:
              #- 'Provision a cluster': provision_cluster.md
              - Install Kubernetes: install_kubernetes.md
              - Exposing your app: exposing.md
              - Deployment options: deploy.md
              - Exposing TCP Services: tcp.md
              - Definitions: "definitions.md"
              - Contributing: contributing.md
extra_css:
      - extra.css
google_analytics: ["UA-131519845-2", "docs.kubesail.com"]
