site_name: KubeSail Docs
theme: readthedocs
repo_url: https://github.com/kubesail/docs
nav:
      - Home: README.md
      - Features:
              - Templates: templates.md
              - Tunneling & DNS: tunneling.md
              - Platform: platform.md
              - Builder: builder.md
              - Backups: backups.md
              - PiBox: pibox.md
      - Changelog: https://kubesail.com/changelog
      - KubeSail Blog: https://kubesail.com/blog
      - Support Chat: https://discord.gg/N3zNdp7jHc
extra_css:
      - extra.css
google_analytics: ["UA-131519845-2", "docs.kubesail.com"]
