apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: kubesail/docs
      context: .
      sync:
        manual:
          - src: docs/**/*
            dest: .
          - src: mkdocs.yml
            dest: .
      docker:
        target: mkdocs
portForward:
  - resourceType: service
    resourceName: docs
    port: 80
    localPort: 8010
