apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubesail-docs
  labels:
    app: docs
spec:
  selector:
    matchLabels:
      app: docs
  minReadySeconds: 1
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: docs
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: docs
          image: kubesail/docs
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: FallbackToLogsOnError
          ports:
            - name: http-ports
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: docs
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http-ports
  selector:
    app: docs
